# crts
crt_domain.key: 
crt_domain_bundle.crt: 
# workspace
host_ip: 172.17.0.1
workspace_path: ../../
apps_dir_name: myapp
domain_name: 
# mysql config
mysql_user: joyousx
mysql_passwd: 123.456
mysql_root_passwd: saturn
# redis config
redis_passwd: 123.456
# wx miniprogram wowoo
wowoo_app_id: 
wowoo_app_secret:  
# wx public account
pubacc_app_id: 
pubacc_app_secret: 
pubacc_app_aeskey: 
pubacc_app_token: 
