from collections import namedtuple

class Rule(object):
    def __init__(self, cpListType, cpLabels, contentLabels, latestLabels=dict(), cpPreType=None):
        # 章节列表中链接拼接方式: raw join_host join_cplist
        self.cpType = cpListType   
        # 章节内容中前后页链接拼接方式: raw join_host join_cplist
        self.cpPreType = cpPreType if cpPreType else cpListType
        self.cpLabels = cpLabels # chapter selector
        self.contentLabels = contentLabels # content selector
        self.latestLabels = latestLabels # latest selector

# 获取小说最新章节
LatestRules = namedtuple('LatestRules', 'plan meta_value selector')
PLAN_01 = LatestRules(
    True,
    {'latest_chapter_name': 'og:novel:latest_chapter_name', 'latest_chapter_url': 'og:novel:latest_chapter_url'},
    None,
)

class ConfigBookSearch(object):
    rules = {
        'www.biquge.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        'www.bequge.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        'www.biquge.info': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}, cpPreType='raw'),
        'www.biqudao.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        'www.biqugex.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),

        # 'www.booktxt.net': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.23txt.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.cc': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.tw': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.com.tw': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.sh': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.co': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.jp': Rule('join_cplist', {'id': 'list'}, {'id': 'content'}),
        # 'www.biquge.tv': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.cm': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.biz': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge.lu': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.biqudao.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.23us.com': Rule('join_cplist', {'id': 'at'}, {'id': 'contents'}),
        # 'www.x23us.com': Rule('join_cplist', {'id': 'at'}, {'id': 'contents'}),
        # 'www.lingdianksw.com': Rule('join_cplist', {'class': 'acss'}, {'id': 'ccontent'}),
        # 'www.qb5200.tw': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # # 'www.zhulang.com': Rule(vip=True),
        # # NOT READY
        # 'www.biquge5200.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquwu.cc': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.quyuege.com': Rule('join_cplist', {'class': 'mod-article-list'}, {'class': 'page-content'}),
        # 'www.bbiquge.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.37zw.net': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquku.la': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.00ksw.org': Rule('join_cplist', {'class': 'ml_list'}, {'id': 'articlecontent'}),
        # 'www.bqge.org': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.aikantxt.la': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquzi.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.bqg.cc': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.vipzw.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.zanghaihuatxt.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.xiuxs.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.1biquge.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xiaoshuowan.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqugela.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqu6.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.zhuaji.org': Rule('join_cplist', {'tag': 'dd'}, {'id': 'content'}),
        # 'www.sqsxs.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquta.com': Rule('https://www.biquta.com/', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xbiquge.la': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.23qb.com': Rule('https://www.23qb.com/', {'id': 'chapterList'}, {'id': 'TextContent'}),
        # 'www.biqugexsw.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.kuxiaoshuo.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.laidudu.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.kanshu58.com': Rule('join_cplist', {'class': 'chapters'}, {'id': 'content'}),
        # 'www.mpxiaoshuo.com': Rule('join_cplist', {'class': 'mulu_list'}, {'id': 'htmlContent'}),
        # 'www.23zw.me': Rule('join_cplist', {'id': 'chapter_list'}, {'id': 'text_area'}),
        # 'www.187ks.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.58xs.tw': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquguan.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xs98.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.kxs7.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.nuomi9.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'book.sfacg.com': Rule('join_host', {'class': 'story-catalog'}, {'tag': 'p'}),
        # 'www.7kshu.com': Rule('join_cplist', {'id': 'chapterlist'}, {'id': 'content'}),
        # 'www.lread.cc': Rule('join_host', {'class': 'box_con'}, {'id': 'booktext'}),
        # 'www.baquge.tw': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqudu.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqugeg.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.ttzw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.zwdu.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.33xs.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.50zw.la': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'htmlContent'}),
        # 'www.44pq.co': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'BookText'}),
        # 'www.wddsnxn.org': Rule('1', {'class': 'booklist'}, {'id': 'BookText'}),
        # 'mianzhuan.wddsnxn.org': Rule('1', {'class': 'booklist'}, {'id': 'BookText'}),
        # 'www.a306.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xs52.com': Rule('join_cplist', {'id': 'chapter_list'}, {'id': 'text_c'}),
        # 'www.xs.la': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.23xsw.cc': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.8jzw.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquguo.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.woquge.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.zhonghuawuxia.com': Rule('1', {'class': 'list'}, {'id': 'content'}),
        # 'www.mytxt.cc': Rule('join_host', {'class': 'story_list_m62topxs'}, {'class': 'detail_con_m62topxs'}),
        # 'www.136txt.com': Rule('1', {'class': 'directory_con'}, {'id': 'chapterContent'}),
        # 'www.xs74.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.yssm.org': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'content'}),
        # 'www.luoxia.com': Rule('1', {'class': 'book-list'}, {'tag': 'p'}),
        # 'www.sbkk88.com': Rule('join_host', {'class': 'leftList'}, {'id': 'f_article'}),
        # 'www.dxsxs.com': Rule('join_host', {'id': 'yuedu'}, {'class': 'zw'}),
        # 'www.wenku8.com': Rule('join_cplist', {'class': 'css'}, {'id': 'content'}),
        # 'www.zuowe.com': Rule('join_host', {'class': 'book_list'}, {'id': 'htmlContent'}),
        # 'www.biqugek.com': Rule('1', {'class': 'book_list'}, {'id': 'htmlContent'}),
        # 'www.wuyanxia.net': Rule('join_host', {'class': 'zjlist4'}, {'id': 'htmlContent'}),
        # 'www.50331.net': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.wenxuemi.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xs222.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.lewen8.com': Rule('join_host', {'id': 'chapterlist'}, {'id': 'content'}),
        # 'www.5ccc.net': Rule('join_cplist', {'class': 'acss'}, {'id': 'content'}),
        # 'www.bqg5200.com': Rule('join_host', {'id': 'readerlist'}, {'id': 'content'}),
        # 'www.vodtw.com': Rule('join_cplist', {'class': 'insert_list'}, {'class': 'contentbox'}),
        # 'www.6mao.com': Rule('join_host', {'class': 'liebiao_bottom'}, {'id': 'neirong'}),
        # 'www.touxiang.la': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.7kankan.com': Rule('join_cplist', {'class': 'uclist'}, {'id': 'content'}),
        # 'www.biqugetw.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'gdbzkz.com': Rule('1', {'class': 'mulu'}, {'class': 'content-body'}),
        # 'www.gdbzkz.com': Rule('1', {'class': 'mulu'}, {'class': 'content-body'}),
        # 'www.freexs.cn': Rule('join_cplist', {'class': 'readout'}, {'class': 'shuneirong'}),
        # 'www.bxquge.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.beidouxin.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.3qzone.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.97xs.net': Rule('1', {'class': 'box'}, {'id': 'htmlContent'}),
        # 'www.7dsw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquge5.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.yooread.com': Rule('join_host', {'id': 'chapterList'}, {'tag': 'p'}),
        # 'www.xs82.com': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'content'}),
        # 'www.kanshuhai.com': Rule('join_cplist', {'id': 'book'}, {'id': 'content'}),
        # 'www.biquku.co': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xbqge.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.aiquxs.com': Rule('join_cplist', {'id': 'list'}, {'id': 'booktext'}),
        # 'www.ttshu.com': Rule('join_host', {'class': 'border'}, {'id': 'content'}),
        # 'www.23wx.cc': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.23wx.cm': Rule('join_cplist', {'class': 'book_list'}, {'id': 'htmlContent'}),
        # 'www.ddbiquge.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.abocms.cn': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.liewen.cc': Rule('https://www.liewen.cc/', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.heiyange.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.8535.org': Rule('join_cplist', {'class': 'booklist'}, {'class': 'txtc'}),
        # 'www.dingdianzw.com': Rule('join_host', {'id': 'bgdiv'}, {'id': 'content'}),
        # 'www.lewenxiaoshuo.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.111bz.org': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqugebook.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.e8zw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.xqqxs.com': Rule('join_cplist', {'class': 'box_con'}, {'class': 'content'}),
        # 'www.139book.com': Rule('join_host', {'class': 'list_box'}, {'class': 'box_box'}),
        # 'www.jcdf99.com': Rule('join_cplist', {'class': 'list_box'}, {'id': 'content'}),
        # 'www.tianzeba.com': Rule('join_host', {'class': 'chapterlist'}, {'id': 'BookText'}),
        # 'www.kanshuwangzhan.com': Rule('join_cplist', {'id': 'chapterlist'}, {'id': 'booktext'}),
        # 'tianyibook.la': Rule('join_host', {'class': 'chapterlist'}, {'id': 'BookText'}),
        # 'www.quanben.net': Rule('join_host', {'class': 'chapterlist'}, {'id': 'BookText'}),
        # 'www.qb5.tw': Rule('join_host', {'class': 'zjbox'}, {'id': 'content'}),
        # 'www.ybdu.com': Rule('join_cplist', {'class': 'mulu_list'}, {'id': 'htmlContent'}),
        # 'www.quanben.com': Rule('join_cplist', {'class': 'mulu_list'}, {'id': 'htmlContent'}),
        # 'www.fhxs.com': Rule('1', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.58xs.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqukan.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.shuyuelou.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.mangg.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.50zw.com': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'htmlContent'}),
        # 'www.lingdiankanshu.co': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqiku.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.duilianku.com': Rule('join_host', {'id': 'list'}, {'class': 'chapter'}),
        # 'www.5xiaxiaoshuo.com': Rule('join_host', {'class': 'art_listmain_main'}, {'id': 'content'}),
        # 'www.81xsw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.wxguan.com': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.fox2008.cn': Rule('join_host', {'class': 'book'}, {'id': 'chapterContent'}),
        # 'www.22zw.com': Rule('join_cplist', {'class': 'acss'}, {'id': 'content'}),
        # 'www.k6uk.com': Rule('join_cplist', {'class': 'acss'}, {'id': 'content'}),
        # 'www.126shu.com': Rule('join_host', {'id': 'list'}, {'id': 'content'}),
        # 'www.kooxs.com': Rule('join_cplist', {'class': 'list'}, {'id': 'content'}),
        # 'www.shubaotxt.com': Rule('join_cplist', {'class': 'list'}, {'id': 'content'}),
        # 'www.muyuge.com': Rule('1', {'id': 'xslist'}, {'id': 'content'}),
        # 'www.biqu.la': Rule('join_cplist', {'class': 'book_list'}, {'id': 'htmlContent'}),
        # 'shushu.com.cn': Rule('join_host', {'id': 'dirsort01'}, {'id': 'content'}),
        # 'www.shuhai.com': Rule('join_cplist', {'class': 'box_chap'}, {'id': 'readcon'}),
        # 'www.37yue.com': Rule('join_cplist', {'class': 'list-chapter'}, {'class': 'chapter'}),
        # 'www.35zw.com': Rule('join_cplist', {'class': 'book_list'}, {'id': 'htmlContent'}),
        # 'www.xinshu.in': Rule('join_host', {'class': 'list_box'}, {'class': 'box_box'}),
        # 'www.lwxs520.com': Rule('join_cplist', {'class': 'dccss'}, {'id': 'content'}),
        # 'www.lwxs.la': Rule('join_host', {'id': 'defaulthtml4'}, {'id': 'content'}),
        # 'www.biqule.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.33yq.com': Rule('1', {'class': 'box_con'}, {'class': 'zhangjieTXT'}),
        # 'www.dishuge.com': Rule('1', {'class': 'update'}, {'tag': 'p'}),
        # 'www.qu.la': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.shuge.net': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.daomengren.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.81zw.net': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.09xs.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.fhxiaoshuo.com': Rule('1', {'class': 'box_con'}, {'class': 'zhangjieTXT'}),
        # 'www.yikanxiaoshuo.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.1xiaoshuo.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.kanshu.la': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.kbiquge.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.00ksw.net': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'wanmeishijiexiaoshuo.org': Rule('1', {'class': 'bg'}, {'class': 'content'}),
        # 'www.sosoxiaoshuo.cc': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.ciluke.com': Rule('join_cplist', {'id': 'list'}, {'id': 'content'}),
        # 'www.81zw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.cilook.net': Rule('join_cplist', {'id': 'cl_content'}, {'id': 'content'}),
        # 'www.baoliny.com': Rule('join_host', {'class': 'readerListShow'}, {'id': 'content'}),
        # 'www.7788xs.net': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.06sy.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqumo.com': Rule('https://www.biqumo.com/', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.kanshuzhe.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biqiuge.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.lwxs.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'TXT'}),
        # 'www.biqugezw.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.shuqizw.com': Rule('join_host', {'class': 'article_texttitleb'}, {'id': 'book_text'}),
        # 'read.ixdzs.com': Rule('join_cplist', {'class': 'catalog'}, {'class': 'content'}),
        # 'www.shumilou.net': Rule('join_cplist', {'class': 'chapterlist'}, {'id': 'BookText'}),
        # 'www.8shuw.com': Rule('1', {'class': 'chapterlist'}, {'id': 'readtext'}),
        # 'www.heiyan.la': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.bbsa5.com': Rule('1', {'class': 'panel'}, {'class': 'content-body'}),
        # 'www.tycqxs.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.miaobige.com': Rule('https://www.miaobige.com/', {'id': 'readerlists'}, {'id': 'content'}),
        # 'www.dashubao.net': Rule('join_cplist', {'class': 'ml_main'}, {'class': 'yd_text2'}),
        # 'www.23zw.com': Rule('join_cplist', {'id': 'chapter_list'}, {'id': 'text_area'}),
        # 'www.23us.la': Rule('join_host', {'class': 'inner'}, {'id': 'content'}),
        # 'www.2952.cc': Rule('join_cplist', {'class': 'inner'}, {'id': 'content'}),
        # 'www.23us.cc': Rule('join_cplist', {'class': 'inner'}, {'id': 'content'}),
        # 'www.13xs.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'booktext'}),
        # 'www.tsxsw.com': Rule('join_cplist', {'class': 'bdsub'}, {'id': 'contents'}),
        # 'www.ymoxuan.com': Rule('1', {'class': 'mulu'}, {'id': 'content'}),
        # 'www.ixs.cc': Rule('https:', {'class': 'mulu'}, {'id': 'content'}),
        # 'zetianjiba.net': Rule('1', {'class': 'bg'}, {'class': 'content'}),
        # 'www.37zw.com': Rule('join_cplist', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.555zw.com': Rule('join_cplist', {'class': 'dir'}, {'id': 'content'}),
        # 'www.jueshitangmen.info': Rule('1', {'class': 'bg'}, {'class': 'content'}),
        # 'www.bxwx9.org': Rule('join_cplist', {'class': 'TabCss'}, {'id': 'content'}),
        # 'www.xxbiquge.com': Rule('https://www.xxbiquge.com/', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.biquwo.com': Rule('https://www.biquwo.com/', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.fs23.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.longtengx.com': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
        # 'www.lingyu.org': Rule('join_host', {'class': 'mt10'}, {'id': 'htmlContent'}),
        # 'www.aszw8.com': Rule('join_cplist', {'id': 'at'}, {'id': 'contents'}),
        # 'www.3zm.net': Rule('join_host', {'class': 'listmain'}, {'id': 'content'}),
        # 'www.kanshuzhong.com': Rule('join_cplist', {'class': 'bookcontent'}, {'class': 'textcontent'}),
        # 'www.siluke.tw': Rule('join_host', {'class': 'box_con'}, {'id': 'content'}),
    }

    rulesLatest = {
        "www.biqugex.com": PLAN_01,
        "www.x23us.com": PLAN_01,
        "www.23us.la": PLAN_01,
        "www.sqsxs.com": PLAN_01,
        "www.nuomi9.com": PLAN_01,
        "www.biquge.info": PLAN_01,
        "www.biquge.tw": PLAN_01,
        "www.qu.la": PLAN_01,
        "www.ybdu.com": PLAN_01,
        "www.wenxuemi.com": PLAN_01,
        "www.biquge.com": PLAN_01,
        "www.23us.cc": PLAN_01,
        "www.xs222.com": PLAN_01,
        "www.lewen8.com": PLAN_01,
        "www.bqg5200.com": PLAN_01,
        "www.vodtw.com": PLAN_01,
        "www.6mao.com": PLAN_01,
        "www.biquge.sh": PLAN_01,
        "www.touxiang.la": PLAN_01,
        "www.bxquge.com": PLAN_01,
        "www.beidouxin.com": PLAN_01,
        "www.biquge.lu": PLAN_01,
        "www.3qzone.com": PLAN_01,
        "wwww.yooread.com": PLAN_01,
        # "www.suimeng.la": PLAN_01,
        "www.bequge.com": PLAN_01,
        "www.biquku.co": PLAN_01,
        "www.xbqge.com": PLAN_01,
        "www.aiquxs.com": PLAN_01,
        "www.23us.com": PLAN_01,
        "www.biqiuge.com": PLAN_01,
        "www.ddbiquge.com": PLAN_01,
        "www.abocms.cn": PLAN_01,
        "www.a306.com": PLAN_01,
        "www.liewen.cc": PLAN_01,
        "www.8535.org": PLAN_01,
        "www.dingdianzw.com": PLAN_01,
        "www.biquge.cc": PLAN_01,
        "www.111bz.org": PLAN_01,
        "www.biqugebook.com": PLAN_01,
        "www.e8zw.com": PLAN_01,
        "www.xqqxs.com": PLAN_01,
        "tianyibook.la": PLAN_01,
        "www.lingdianksw.com": PLAN_01,
        "www.qb5.tw": PLAN_01,
        "www.quanben.com": PLAN_01,
        "www.58xs.com": PLAN_01,
        "www.biqukan.com": PLAN_01,
        "www.yssm.org": PLAN_01,
        "www.81zw.com": PLAN_01,
        "www.ymoxuan.com": PLAN_01,
        "www.mytxt.cc": PLAN_01,
        "www.woquge.com": PLAN_01,
        "www.biquguo.com": PLAN_01,
        "www.8jzw.cc": PLAN_01,
        "www.biquge.tv": PLAN_01,
        "www.biquge5200.com": PLAN_01,
        "www.8jzw.com": PLAN_01,
        "www.23xsw.cc": PLAN_01,
        "www.miaobige.com": PLAN_01,
        "www.xs.la": PLAN_01,
        "www.44pq.co": PLAN_01,
        "www.50zw.la": PLAN_01,
        "www.33xs.com": PLAN_01,
        "www.zwdu.com": PLAN_01,
        "www.ttzw.com": PLAN_01,
        "www.zanghaihuatxt.com": PLAN_01,
        "www.kuxiaoshuo.com": PLAN_01,
        "www.biqudu.com": PLAN_01,
        "www.biqugeg.com": PLAN_01,
        "www.23txt.com": PLAN_01,
        "www.baquge.tw": PLAN_01,
        "www.23qb.com": PLAN_01,
        "www.lread.cc": PLAN_01,
        "www.biqudao.com": PLAN_01,
        "www.laidudu.com": PLAN_01,
        "www.kxs7.com": PLAN_01,
        "www.biquguan.com": PLAN_01,
        "www.biquta.com": PLAN_01,
        "www.xs98.com": PLAN_01,
        "www.bqge.org": PLAN_01,
        "www.58xs.tw": PLAN_01,
        "www.187ks.com": PLAN_01,
        "www.yikanxiaoshuo.com": PLAN_01,
        "www.23zw.me": PLAN_01,
        "www.37zw.net": PLAN_01,
        "www.biquge.cm": PLAN_01,
        "www.kanshu58.com": PLAN_01,
        "www.biqumo.com": PLAN_01,
        "www.mpxiaoshuo.com": PLAN_01,
        "www.23wx.cm": PLAN_01,
        "www.biquge.jp": PLAN_01,
        "www.biqugexsw.com": PLAN_01,
        "www.biqu6.com": PLAN_01,
        "www.xiuxs.com": PLAN_01,
        "www.booktxt.net": PLAN_01,
        "www.biqule.com": PLAN_01,
        "www.biquzi.com": PLAN_01,
        "www.biquku.la": PLAN_01,
        "www.00ksw.org": PLAN_01,
        "www.bqg.cc": PLAN_01,
        "www.biqugezw.com": PLAN_01,
        "www.bbiquge.com": PLAN_01,
        "www.aikantxt.la": PLAN_01,
        "www.biquge.com.tw": PLAN_01,
        "www.xxbiquge.com": PLAN_01,
        "www.biquwo.com": PLAN_01,
        "www.ixs.cc": PLAN_01,
    }
    
    # 针对某些网站检索出来的地址和真正的目录地址不一样从而进行替换
    rulesReplace = {
        "www.miaobige.com": {
            'old': 'miaobige.com/book/',
            'new': 'miaobige.com/read/'
        },
        "www.5ccc.net": {
            'old': '5ccc.net/wksz_info/',
            'new': '5ccc.net/xiaoshuo/'
        },
        "www.7kankan.com": {
            'old': '7kankan.com/files/article/info/',
            'new': '7kankan.com/files/article/html/'
        },
        "www.wuyanxia.net": {
            'old': 'wuyanxia.net/book/',
            'new': 'wuyanxia.net/read/'
        },
    }
