version: '3'
services:
  mysql:
    # 指定容器名称后，该服务将无法进行扩展（scale），因为 Docker 不允许多个容器具有相同的名称。
    container_name: mysql.5.7
    restart: always
    image: 'mysql:5.7'
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=apps
      - MYSQL_USER={mysql_user}
      - MYSQL_PASSWORD={mysql_passwd}
      - MYSQL_ROOT_PASSWORD={mysql_root_passwd}
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  redis:
    container_name: redis.5
    restart: always
    image: 'redis:5.0'
    ports:
      - '6379:6379'
    volumes:
      - /data/redis:/data
      #- ./redis.conf:/usr/local/etc/redis/redis.conf   挂载配置文件
    command: --requirepass '{redis_passwd}'
    environment:
      - Debug=true

  nginx:
    depends_on:
      - mysql
      - redis
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - redis
      - mysql
    volumes:
      - {workspace_path}/{apps_dir_name}/:/data/{apps_dir_name}/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../crts/{crt_domain.key}:/etc/nginx/{crt_domain.key}:ro
      - ../crts/{crt_domain_bundle.crt}:/etc/nginx/{crt_domain_bundle.crt}:ro
    command: [nginx-debug, '-g', 'daemon off;']
